"""
Brand routes.
POST /api/v1/brands/             - Trigger brand onboarding
GET  /api/v1/brands/{brand_id}  - Fetch brand details
GET  /api/v1/brands/crafts      - List all available craft types
"""

import json
import logging
import uuid
from pathlib import Path
import io
import zipfile

import httpx
from fastapi import APIRouter, BackgroundTasks, Depends, File, HTTPException, UploadFile, status
from pydantic import BaseModel

from app.agents.nodes.context_builder import context_builder_node
from app.services.asset_prompt_service import build_brand_asset_prompt, build_brand_visual_dna
from app.services.gemini_image_service import generate_image
from app.services.groq_client import groq_json_completion

from app.agents.graphs.brand_graph import run_brand_graph
from app.agents.state import BrandState
from app.api.deps import get_current_user_id
from app.core.database import supabase
from app.models.brand import BrandCreateRequest, BrandPublic, CraftInfo
from app.models.job import JobCreateResponse
from app.services.storage_service import upload_bytes

logger = logging.getLogger(__name__)
router = APIRouter()

LIBRARY_DIR = Path("data/craft_library")
FEEL_LOGO_STYLE = {
    "earthy": "organic, rooted, warm, textured, artisan-luxury",
    "royal": "ornate, regal, jewel-toned, heritage-inspired, premium",
    "vibrant": "bold, playful, celebratory, high-contrast, folk-art energy",
    "minimal": "restrained, refined, spacious, modern, editorial",
}

FEEL_BANNER_STYLE = {
    "earthy": "muted terracotta, ochre, soft handmade textures, grounded craft atmosphere",
    "royal": "deep jewel tones, elegant detailing, premium heritage mood, decorative richness",
    "vibrant": "colorful celebratory craft textures, bright contrast, dynamic pattern rhythm",
    "minimal": "airy composition, subtle material texture, modern luxury, one strong accent",
}


class RegenerateAssetRequest(BaseModel):
    asset_type: str


def _build_state_from_brand(job_id: str, user_id: str, brand: dict) -> BrandState:
    return {
        "job_id": job_id,
        "brand_id": brand["id"],
        "user_id": user_id,
        "craft_id": brand.get("craft_id", ""),
        "artisan_name": brand.get("artisan_name", "") or "",
        "region": brand.get("region", "") or "",
        "years_of_experience": brand.get("years_of_experience", 0) or 0,
        "generations_in_craft": brand.get("generations_in_craft", 1) or 1,
        "primary_occasion": brand.get("primary_occasion", "general") or "general",
        "target_customer": brand.get("target_customer", "local_bazaar") or "local_bazaar",
        "brand_feel": brand.get("brand_feel", "earthy") or "earthy",
        "script_preference": brand.get("script_preference", "both") or "both",
        "artisan_story": brand.get("artisan_story"),
        "preferred_language": brand.get("preferred_language", "hi") or "hi",
        "reference_images": brand.get("reference_images", []),
        "brand_name": brand.get("name", "") or "",
        "tagline": brand.get("tagline", "") or "",
        "palette": brand.get("palette", {}) or {},
        "story_en": brand.get("story_en", "") or "",
        "story_hi": brand.get("story_hi", "") or "",
        "logo_url": brand.get("logo_url", "") or "",
        "banner_url": brand.get("banner_url", "") or "",
        "kit_zip_url": brand.get("kit_zip_url", "") or "",
    }


async def _download_public_file(url: str) -> bytes:
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(url)
        response.raise_for_status()
        return response.content


async def _rebuild_brand_kit(brand_id: str, state: BrandState) -> str:
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        if state.get("logo_url"):
            archive.writestr("logo.png", await _download_public_file(state["logo_url"]))
        if state.get("banner_url"):
            archive.writestr("banner.png", await _download_public_file(state["banner_url"]))
        archive.writestr("brand_story_en.txt", state.get("story_en", ""))
        archive.writestr("brand_story_hi.txt", state.get("story_hi", ""))
        archive.writestr("palette.json", json.dumps(state.get("palette", {}), indent=2))
        archive.writestr(
            "README.md",
            (
                f"# {state.get('brand_name')} - Brand Kit\n\n"
                f"Tagline: {state.get('tagline')}\n"
                f"Craft: {state.get('craft_id', '').replace('_', ' ').title()}\n"
                "Generated by Idanta\n"
            ),
        )

    return await upload_bytes(
        data=zip_buffer.getvalue(),
        path=f"brands/{brand_id}/brand_kit.zip",
        content_type="application/zip",
    )


async def _regenerate_logo_or_banner(state: BrandState, asset_type: str) -> str:
    visual_dna = await build_brand_visual_dna(state)
    if asset_type == "logo":
        prompt = (
            build_brand_asset_prompt(state, visual_dna, "logo")
            + f"\nStyle modifier: {FEEL_LOGO_STYLE.get(state.get('brand_feel', 'earthy'), FEEL_LOGO_STYLE['earthy'])}."
        )
        image_bytes, mime = await generate_image(prompt, width_hint=1024, height_hint=1024)
        return await upload_bytes(
            data=image_bytes,
            path=f"brands/{state['brand_id']}/logo.png",
            content_type=mime,
        )
    prompt = (
        build_brand_asset_prompt(state, visual_dna, "banner")
        + f"\nStyle modifier: {FEEL_BANNER_STYLE.get(state.get('brand_feel', 'earthy'), FEEL_BANNER_STYLE['earthy'])}."
    )
    image_bytes, mime = await generate_image(prompt, width_hint=1536, height_hint=768)
    return await upload_bytes(
        data=image_bytes,
        path=f"brands/{state['brand_id']}/banner.png",
        content_type=mime,
    )


async def _regenerate_tagline(state: BrandState) -> str:
    context = state.get("context_bundle", {})
    result = await groq_json_completion(
        system_prompt=(
            "You are an expert Indian artisan brand copywriter.\n"
            "Output only JSON: {\"tagline\": \"...\"}\n"
            "Rules: keep it under 8 words, premium tone, specific to craft, non-generic."
        ),
        user_prompt=(
            f"Brand name: {state.get('brand_name')}\n"
            f"Craft: {context.get('craft_name', state.get('craft_id', '').replace('_', ' ').title())}\n"
            f"Region: {context.get('region')}\n"
            f"Brand feel: {context.get('brand_feel', 'earthy')}\n"
            f"Target customer: {context.get('target_customer', 'local_bazaar')}\n"
            f"Script preference: {context.get('script_preference', 'both')}\n"
            f"Artisan story: {context.get('artisan_story', '')}\n"
            f"Current tagline: {state.get('tagline', '')}\n"
            f"RAG context: {state.get('rag_context', '')}"
        ),
        max_tokens=120,
        temperature=0.7,
    )
    return str(result.get("tagline") or state.get("tagline") or "").strip()


async def _run_targeted_regeneration(job_id: str, user_id: str, brand: dict, asset_type: str) -> None:
    try:
        state = _build_state_from_brand(job_id, user_id, brand)
        supabase.table("jobs").update(
            {
                "status": "running",
                "current_step": f"Preparing {asset_type} regeneration...",
                "percent": 15,
            }
        ).eq("id", job_id).execute()

        state = await context_builder_node(state)
        updates: dict = {}

        if asset_type in ("logo", "banner"):
            supabase.table("jobs").update(
                {
                    "current_step": f"Regenerating brand {asset_type}...",
                    "percent": 55,
                }
            ).eq("id", job_id).execute()
            generated_url = await _regenerate_logo_or_banner(state, asset_type)
            updates[f"{asset_type}_url"] = generated_url
            state[f"{asset_type}_url"] = generated_url
        elif asset_type == "tagline":
            supabase.table("jobs").update(
                {
                    "current_step": "Regenerating tagline...",
                    "percent": 55,
                }
            ).eq("id", job_id).execute()
            tagline = await _regenerate_tagline(state)
            updates["tagline"] = tagline
            state["tagline"] = tagline
        else:
            raise ValueError("Unsupported asset type.")

        supabase.table("jobs").update(
            {
                "current_step": "Refreshing brand kit...",
                "percent": 85,
            }
        ).eq("id", job_id).execute()
        kit_zip_url = await _rebuild_brand_kit(brand["id"], state)
        updates["kit_zip_url"] = kit_zip_url

        supabase.table("brands").update(updates).eq("id", brand["id"]).eq("user_id", user_id).execute()
        supabase.table("jobs").update(
            {
                "status": "done",
                "current_step": f"{asset_type.title()} regenerated.",
                "percent": 100,
                "ref_id": brand["id"],
            }
        ).eq("id", job_id).execute()
    except Exception as exc:
        logger.error("Targeted brand regeneration failed (asset=%s): %s", asset_type, exc)
        supabase.table("jobs").update(
            {
                "status": "failed",
                "current_step": "Something went wrong",
                "error": f"Could not regenerate {asset_type}. Please try again.",
            }
        ).eq("id", job_id).execute()


def _list_crafts() -> list[CraftInfo]:
    crafts: list[CraftInfo] = []
    for file_path in LIBRARY_DIR.glob("*.json"):
        try:
            with open(file_path, encoding="utf-8") as file:
                data = json.load(file)
            crafts.append(
                CraftInfo(
                    craft_id=data["craft_id"],
                    display_name=data.get("display_name", data["craft_id"]),
                    region=data.get("region", "India"),
                    description=data.get("description", ""),
                )
            )
        except Exception as exc:
            logger.warning("Failed to parse craft file %s: %s", file_path.name, exc)
    return crafts


@router.get(
    "/crafts",
    response_model=list[CraftInfo],
    summary="List all supported craft types",
    tags=["Crafts"],
)
async def get_crafts():
    return _list_crafts()


@router.post(
    "/",
    response_model=JobCreateResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Start brand onboarding",
    tags=["Brands"],
)
async def create_brand(
    payload: BrandCreateRequest,
    background_tasks: BackgroundTasks,
    user_id: str = Depends(get_current_user_id),
):
    pending = (
        supabase.table("jobs")
        .select("id")
        .eq("user_id", user_id)
        .eq("job_type", "brand_onboarding")
        .in_("status", ["queued", "running"])
        .execute()
    )
    if pending.data:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="A brand creation job is already in progress for this account.",
        )

    job_result = (
        supabase.table("jobs")
        .insert(
            {
                "user_id": user_id,
                "job_type": "brand_onboarding",
                "status": "queued",
                "current_step": "Job queued...",
                "percent": 0,
            }
        )
        .execute()
    )
    job_id = job_result.data[0]["id"]

    initial_state: BrandState = {
        "job_id": job_id,
        "user_id": user_id,
        "craft_id": payload.craft_id,
        "artisan_name": payload.artisan_name,
        "region": payload.region,
        "years_of_experience": payload.years_of_experience,
        "generations_in_craft": payload.generations_in_craft,
        "primary_occasion": payload.primary_occasion.value,
        "target_customer": payload.target_customer.value,
        "brand_feel": payload.brand_feel.value,
        "script_preference": payload.script_preference.value,
        "artisan_story": payload.artisan_story,
        "preferred_language": payload.preferred_language,
        "reference_images": payload.reference_images,
    }

    background_tasks.add_task(run_brand_graph, initial_state)

    logger.info("Brand onboarding job enqueued: job_id=%s, user_id=%s", job_id, user_id)
    return JobCreateResponse(
        job_id=job_id,
        message="Brand creation started. Poll /api/v1/jobs/{job_id}/status for progress.",
    )


@router.post(
    "/upload-images",
    response_model=list[str],
    summary="Upload reference images for brand onboarding",
    tags=["Brands"],
)
async def upload_brand_images(
    photos: list[UploadFile] = File(...),
    user_id: str = Depends(get_current_user_id),
):
    photo_urls: list[str] = []
    session_id = str(uuid.uuid4())[:8]
    for index, photo in enumerate(photos[:3]):
        content = await photo.read()
        ext = photo.filename.rsplit(".", 1)[-1] if photo.filename and "." in photo.filename else "jpg"
        storage_path = f"brands/temp_{user_id}/{session_id}_{index}.{ext}"
        url = await upload_bytes(
            data=content,
            path=storage_path,
            content_type=photo.content_type or "image/jpeg",
        )
        photo_urls.append(url)
    return photo_urls


@router.get(
    "/{brand_id}",
    response_model=BrandPublic,
    summary="Get brand by ID",
    tags=["Brands"],
)
async def get_brand(
    brand_id: str,
    user_id: str = Depends(get_current_user_id),
):
    result = (
        supabase.table("brands")
        .select("*")
        .eq("id", brand_id)
        .eq("user_id", user_id)
        .single()
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Brand not found.")
    return result.data


@router.post(
    "/{brand_id}/generate",
    response_model=JobCreateResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Regenerate brand assets for an existing brand",
    tags=["Brands"],
)
async def regenerate_brand(
    brand_id: str,
    background_tasks: BackgroundTasks,
    user_id: str = Depends(get_current_user_id),
):
    result = (
        supabase.table("brands")
        .select("*")
        .eq("id", brand_id)
        .eq("user_id", user_id)
        .single()
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Brand not found.")

    pending = (
        supabase.table("jobs")
        .select("id")
        .eq("user_id", user_id)
        .eq("job_type", "brand_onboarding")
        .eq("ref_id", brand_id)
        .in_("status", ["queued", "running"])
        .execute()
    )
    if pending.data:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Brand assets are already being generated.",
        )

    brand = result.data
    job_result = (
        supabase.table("jobs")
        .insert(
            {
                "user_id": user_id,
                "job_type": "brand_onboarding",
                "ref_id": brand_id,
                "status": "queued",
                "current_step": "Job queued...",
                "percent": 0,
            }
        )
        .execute()
    )
    job_id = job_result.data[0]["id"]

    initial_state: BrandState = {
        "job_id": job_id,
        "brand_id": brand_id,
        "user_id": user_id,
        "craft_id": brand["craft_id"],
        "artisan_name": brand.get("artisan_name") or "",
        "region": brand.get("region") or "",
        "years_of_experience": brand.get("years_of_experience", 0),
        "generations_in_craft": brand.get("generations_in_craft", 1),
        "primary_occasion": brand.get("primary_occasion", "general"),
        "target_customer": brand.get("target_customer", "local_bazaar"),
        "brand_feel": brand.get("brand_feel", "earthy"),
        "script_preference": brand.get("script_preference", "both"),
        "artisan_story": brand.get("artisan_story"),
        "preferred_language": brand.get("preferred_language", "hi"),
        "reference_images": brand.get("reference_images", []),
    }

    background_tasks.add_task(run_brand_graph, initial_state)

    logger.info("Brand regeneration job enqueued: job_id=%s, brand_id=%s", job_id, brand_id)
    return JobCreateResponse(
        job_id=job_id,
        message="Brand regeneration started. Poll /api/v1/jobs/{job_id}/status for progress.",
    )


@router.post(
    "/{brand_id}/regenerate-asset",
    response_model=JobCreateResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Regenerate a specific brand asset",
    tags=["Brands"],
)
async def regenerate_brand_asset(
    brand_id: str,
    payload: RegenerateAssetRequest,
    background_tasks: BackgroundTasks,
    user_id: str = Depends(get_current_user_id),
):
    asset_type = payload.asset_type.strip().lower()
    if asset_type not in {"logo", "banner", "tagline"}:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="asset_type must be logo, banner, or tagline.")

    result = (
        supabase.table("brands")
        .select("*")
        .eq("id", brand_id)
        .eq("user_id", user_id)
        .single()
        .execute()
    )
    if not result.data:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Brand not found.")
    brand = result.data

    pending = (
        supabase.table("jobs")
        .select("id")
        .eq("user_id", user_id)
        .eq("job_type", "brand_onboarding")
        .eq("ref_id", brand_id)
        .in_("status", ["queued", "running"])
        .execute()
    )
    if pending.data:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="A brand generation job is already in progress.",
        )

    job_result = (
        supabase.table("jobs")
        .insert(
            {
                "user_id": user_id,
                "job_type": "brand_onboarding",
                "ref_id": brand_id,
                "status": "queued",
                "current_step": f"Queued {asset_type} regeneration...",
                "percent": 0,
            }
        )
        .execute()
    )
    job_id = job_result.data[0]["id"]
    background_tasks.add_task(_run_targeted_regeneration, job_id, user_id, brand, asset_type)
    return JobCreateResponse(
        job_id=job_id,
        message=f"{asset_type.title()} regeneration started. Poll /api/v1/jobs/{job_id}/status for progress.",
    )
