"""
Packager Node - Final step in both brand and product graphs.
"""

import io
import json
import logging
import zipfile

import httpx

from app.agents.state import BrandState, ProductState
from app.core.database import supabase
from app.services.storage_service import upload_bytes

logger = logging.getLogger(__name__)


async def _download_public_file(url: str) -> bytes:
    async with httpx.AsyncClient(timeout=30.0) as client:
        response = await client.get(url)
        response.raise_for_status()
        return response.content


async def packager_brand_node(state: BrandState) -> BrandState:
    """Persist brand data, create Brand Kit ZIP, and mark job as done."""
    job_id = state["job_id"]
    user_id = state["user_id"]
    existing_brand_id = state.get("brand_id")

    supabase.table("jobs").update(
        {
            "current_step": "Packaging your brand kit...",
            "percent": 90,
        }
    ).eq("id", job_id).execute()

    brand_record = {
        "user_id": user_id,
        "craft_id": state.get("craft_id"),
        "artisan_name": state.get("artisan_name"),
        "region": state.get("region"),
        "preferred_language": state.get("preferred_language"),
        "reference_images": state.get("reference_images", []),
        "generations_in_craft": state.get("generations_in_craft", 1),
        "years_of_experience": state.get("years_of_experience", 0),
        "primary_occasion": state.get("primary_occasion", "general"),
        "target_customer": state.get("target_customer", "local_bazaar"),
        "brand_feel": state.get("brand_feel", "earthy"),
        "artisan_story": state.get("artisan_story"),
        "script_preference": state.get("script_preference", "both"),
        "visual_summary": state.get("visual_summary"),
        "visual_motifs": state.get("visual_motifs", []),
        "signature_patterns": state.get("signature_patterns", []),
        "name": state.get("brand_name"),
        "tagline": state.get("tagline"),
        "palette": state.get("palette"),
        "story_en": state.get("story_en"),
        "story_hi": state.get("story_hi"),
        "logo_url": state.get("logo_url"),
        "banner_url": state.get("banner_url"),
        "status": "ready",
    }
    if existing_brand_id:
        supabase.table("brands").update(brand_record).eq("id", existing_brand_id).execute()
        brand_id = existing_brand_id
    else:
        response = supabase.table("brands").insert(brand_record).execute()
        brand_id = response.data[0]["id"]

    supabase.table("users").update({"has_brand": True}).eq("id", user_id).execute()

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        if state.get("logo_url"):
            archive.writestr("logo.png", await _download_public_file(state["logo_url"]))
        if state.get("banner_url"):
            archive.writestr("banner.png", await _download_public_file(state["banner_url"]))
        archive.writestr("brand_story_en.txt", state.get("story_en", ""))
        archive.writestr("brand_story_hi.txt", state.get("story_hi", ""))
        archive.writestr("palette.json", json.dumps(state.get("palette", {}), indent=2))
        archive.writestr(
            "README.md",
            (
                f"# {state.get('brand_name')} - Brand Kit\n\n"
                f"Tagline: {state.get('tagline')}\n"
                f"Craft: {state.get('craft_id', '').replace('_', ' ').title()}\n"
                f"Generated by Idanta\n"
            ),
        )

    kit_zip_url = await upload_bytes(
        data=zip_buffer.getvalue(),
        path=f"brands/{brand_id}/brand_kit.zip",
        content_type="application/zip",
    )

    supabase.table("brands").update({"kit_zip_url": kit_zip_url, "logo_url": state.get("logo_url")}).eq("id", brand_id).execute()
    supabase.table("jobs").update(
        {
            "status": "done",
            "current_step": "Brand kit ready!",
            "percent": 100,
            "ref_id": brand_id,
        }
    ).eq("id", job_id).execute()

    logger.info("Brand packager complete: brand_id=%s, job=%s", brand_id, job_id)
    return {
        **state,
        "brand_id": brand_id,
        "logo_url": state.get("logo_url", ""),
        "kit_zip_url": kit_zip_url,
    }


async def packager_product_node(state: ProductState) -> ProductState:
    """Persist product asset URLs, build product kit ZIP, and mark job as done."""
    job_id = state["job_id"]
    product_id = state["product_id"]

    supabase.table("jobs").update(
        {
            "current_step": "Finalizing your product assets...",
            "percent": 90,
        }
    ).eq("id", job_id).execute()

    print_asset_paths = state.get("print_asset_paths", {})
    asset_sources: dict[str, str] = {
        "hang_tag.png": state.get("hang_tag_url") or print_asset_paths.get("hang_tag", ""),
        "label.png": state.get("label_url") or print_asset_paths.get("label", ""),
        "story_card.png": print_asset_paths.get("story_card", ""),
        "certificate.png": print_asset_paths.get("certificate", ""),
        "branded_photo.png": state.get("branded_photo_url", ""),
    }

    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("listing_copy.txt", state.get("listing_copy", "") or "")
        archive.writestr("social_caption.txt", state.get("social_caption", "") or "")
        archive.writestr("care_instructions.txt", state.get("care_instructions", "") or "")
        archive.writestr(
            "README.md",
            (
                f"# {state.get('product_name', 'Product')} - Product Asset Kit\n\n"
                f"Brand: {state.get('brand_name', 'Idanta Brand')}\n"
                f"Category: {state.get('product_category', 'other')}\n"
                f"Occasion: {state.get('occasion', 'general')}\n"
                "Included files are ready for packaging, printing, and basic marketing use.\n"
            ),
        )

        for filename, url in asset_sources.items():
            if not url:
                continue
            try:
                archive.writestr(filename, await _download_public_file(url))
            except Exception as exc:
                logger.warning("Could not add %s to product asset zip for product=%s: %s", filename, product_id, exc)

    kit_zip_url = await upload_bytes(
        data=zip_buffer.getvalue(),
        path=f"products/{product_id}/product_asset_kit.zip",
        content_type="application/zip",
    )

    supabase.table("products").update(
        {
            "listing_copy": state.get("listing_copy"),
            "branded_photo_url": state.get("branded_photo_url"),
            "hang_tag_url": state.get("hang_tag_url") or print_asset_paths.get("hang_tag"),
            "label_url": state.get("label_url") or print_asset_paths.get("label"),
            "kit_zip_url": kit_zip_url,
            "story_card_url": print_asset_paths.get("story_card"),
            "certificate_url": print_asset_paths.get("certificate"),
            "status": "ready",
        }
    ).eq("id", product_id).execute()

    supabase.table("jobs").update(
        {
            "status": "done",
            "current_step": "Product assets ready!",
            "percent": 100,
            "ref_id": product_id,
        }
    ).eq("id", job_id).execute()

    logger.info("Product packager complete: product_id=%s, job=%s", product_id, job_id)
    return {**state, "kit_zip_url": kit_zip_url, "assets_zip_url": kit_zip_url}
