"""
Packager Node — Final step in both brand and product graphs.

Brand Packager:
- Writes brand data to the `brands` DB table
- Creates a ZIP of logo.svg + banner + stories
- Uploads ZIP to Supabase Storage
- Updates job to 100% / done

Product Packager:
- Writes product asset URLs to the `products` DB table
- Updates job to 100% / done
"""

import io
import json
import logging
import uuid
import zipfile

from app.agents.state import BrandState, ProductState
from app.core.database import supabase
from app.services.storage_service import upload_bytes

logger = logging.getLogger(__name__)


async def packager_brand_node(state: BrandState) -> BrandState:
    """
    Persist brand data, create Brand Kit ZIP, and mark job as done.
    """
    job_id = state["job_id"]
    user_id = state["user_id"]

    supabase.table("jobs").update({
        "current_step": "📦 Packaging your brand kit...",
        "percent": 90,
    }).eq("id", job_id).execute()

    # 1. Insert brand record into DB
    brand_record = {
        "user_id": user_id,
        "craft_id": state.get("craft_id"),
        "name": state.get("brand_name"),
        "tagline": state.get("tagline"),
        "palette": state.get("palette"),
        "story_en": state.get("story_en"),
        "story_hi": state.get("story_hi"),
        "logo_url": state.get("logo_url"),
        "banner_url": state.get("banner_url"),
        "status": "ready",
    }
    response = supabase.table("brands").insert(brand_record).execute()
    brand_id = response.data[0]["id"]

    # 2. Update user's has_brand flag
    supabase.table("users").update({"has_brand": True}).eq("id", user_id).execute()

    # 3. Rename uploaded assets to use real brand_id
    # (Re-uploading to permanent path under the real brand_id)
    logo_content = state.get("logo_svg", "").encode("utf-8")
    logo_url = await upload_bytes(
        data=logo_content,
        path=f"brands/{brand_id}/logo.svg",
        content_type="image/svg+xml",
    )

    # 4. Create Brand Kit ZIP
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("logo.svg", state.get("logo_svg", ""))
        zf.writestr("brand_story_en.txt", state.get("story_en", ""))
        zf.writestr("brand_story_hi.txt", state.get("story_hi", ""))
        palette_json = json.dumps(state.get("palette", {}), indent=2)
        zf.writestr("palette.json", palette_json)
        readme = (
            f"# {state.get('brand_name')} — Brand Kit\n\n"
            f"**Tagline:** {state.get('tagline')}\n\n"
            f"**Craft:** {state.get('craft_id', '').replace('_', ' ').title()}\n\n"
            f"Generated by Idanta — Brand-in-a-Box for Indian Artisans\n"
        )
        zf.writestr("README.md", readme)

    zip_bytes = zip_buffer.getvalue()
    kit_zip_url = await upload_bytes(
        data=zip_bytes,
        path=f"brands/{brand_id}/brand_kit.zip",
        content_type="application/zip",
    )

    # 5. Update brand record with the zip URL and real logo URL
    supabase.table("brands").update({
        "kit_zip_url": kit_zip_url,
        "logo_url": logo_url,
    }).eq("id", brand_id).execute()

    # 6. Mark job as done
    supabase.table("jobs").update({
        "status": "done",
        "current_step": "✅ Brand kit ready!",
        "percent": 100,
        "ref_id": brand_id,
    }).eq("id", job_id).execute()

    logger.info(f"Brand packager complete: brand_id={brand_id}, job={job_id}")

    return {
        **state,
        "brand_id": brand_id,
        "logo_url": logo_url,
        "kit_zip_url": kit_zip_url,
    }


async def packager_product_node(state: ProductState) -> ProductState:
    """Persist product asset URLs and mark job as done."""
    job_id = state["job_id"]
    product_id = state["product_id"]

    supabase.table("jobs").update({
        "current_step": "📦 Finalizing your product assets...",
        "percent": 90,
    }).eq("id", job_id).execute()

    # Update product record with all generated asset URLs
    supabase.table("products").update({
        "listing_copy": state.get("listing_copy"),
        "branded_photo_url": state.get("branded_photo_url"),
        "hang_tag_url": state.get("hang_tag_url"),
        "label_url": state.get("label_url"),
        "status": "ready",
    }).eq("id", product_id).execute()

    # Mark job as done
    supabase.table("jobs").update({
        "status": "done",
        "current_step": "✅ Product assets ready!",
        "percent": 100,
        "ref_id": product_id,
    }).eq("id", job_id).execute()

    logger.info(f"Product packager complete: product_id={product_id}, job={job_id}")

    return {**state, "assets_zip_url": ""}
